### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by PARODBE** [CoAxLab/pycombat#1]
Hi,

first at all thank you for the code! Could you provide some example code using your code please? An example notebook using fit_transform for training series and transform for test set join 2 or 3 datasets with batch effect. please?

Thanks

Pablo

**Comment by jrasero** [comment]
Hola Pablo,

First of all, thanks for your interest in pycombat. Second of all, sorry that I missed your message. I was not getting any notifications.

You have a Jupyter notebook with a demo in the test folder in this repo. Let me know if that's enough for you or not. If not, we can work out something else.

**Comment by PARODBE** [comment]
Hi Jrasero,

It is true, I saw it after. But I have a question. How you build your definitive dataset for pycombat when you have two datasets with different columns and rows (a big batch effect...)? Thanks!

**Comment by jrasero** [comment]
Closed because this was solved off-line
